const GLOBAL_CONSTANT = {
  PSP_MODAL_STATUS: {
    NO_PSP_INSTALLED: "NO_PSP_INSTALLED",
    INVALID_PARAMS: "INVALID_PARAMS",
    USER_CLOSED: "USER_CLOSED",
  },
  API_STATUS: {
    SUCCESS: 1,
    LOADING: 0,
    FAIL: -1,
  },
  STATUS_REFRESH_API_TIMEOUT: 10000,
  STATUS_REFRESH_API_MAX_COUNT: 60,
  STATUS_CONSTANT: {
    success: "Successful",
    failed: "Failed",
    failure: "Failed",
    pending: "Pending",
    cancelled: "Cancelled",
    parked: "Successful",
  },
  POSTPE_DEEPLINK: "postpe://dynamic?key=home",
  GV_DEEPLINK: "postpe://dynamic?key=postpe-gv-uat2",
  WROUTE: {
    OFFERS: "offers",
    TNC: "tnc",
    REFER_N_EARN: "refernearn",
    SCAN_N_PAY: "scanPay",
    TXN_STATUS: "txnStatus",
    SEND_MONEY: "sendMoney",
    LIMITS: "limits",
    CASHBACK: "cashBack",
    CRM_PAYMENT_LINK: "crmPaymentLink",
    GAANA_OFFER: "gaanaOffer",
    SANCTION_LETTER: "sanctionLetter",
    STATUS_SCREEN: "status",
  },
  URL_PARAMETER: {
    WROUTE: "wroute",
    ORDER_ID: "order_id",
    TXN_ID: "txnId",
    APPVERSION: "appversion",
    CID: "cid",
    CONSUMER_ID: "consumerId",
    DEVICE_ID: "deviceId",
    INSTALL_ID: "installId",
    IS_VIRTUAL: "is_virtual",
    LATITUDE: "latitude",
    LONGITUDE: "longitude",
    MANUFACTURER: "manufacturer",
    MODEL: "model",
    PLATFORM: "platform",
    ROUTING_KEY: "routing_key",
    SERIAL: "serial",
    SIM_ID: "simId",
    TOKEN: "token",
    VERSION: "version",
    VISA: "visa",
  },

  ROUTE_CHANGE_TRANSITION_TIME: 250,
  CDN: "",
  MINIMUM_JUSPAY_VERSION: {
		ANDROID: 125,
		IOS: 113,
	},
};
export default GLOBAL_CONSTANT;
