export const globalStyles = {
	clrPrimary: { color: 'var(--theme-primary)' },
	clrDisabled: { color: 'var(--disabled-color)' },
	clrBlack: { color: 'var(--black)' },
	clrWhite: { color: 'var(--white)' },
	clrRed: { color: 'var(--red)' },
	clrPurple: { color: 'var(--purple)' },
	clrGray: { color: 'var(--dark-gray)' },
	clrGreen: { color: 'var(--green)' },
	clrYellow: { color: 'var(--yellow)' },
	clrPink: { color: 'var(--pink)' },
	clrLightBlack: { color: 'var(--light-black)' },
	transparent: { color: 'transparent' },
	clrLightGray: { color: 'var(--light-gray)' },
	bgWhite: { background: 'var(--white)' },
	bgWhiteImportant: { background: 'var(--white) !important' },
	bgPink: { background: 'var(--pink)' },
	bgBlack: { background: 'var(--black)' },
	bgTransparent: { background: 'transparent !important' },
	bgDarkBlue: { background: 'var(--theme-primary)' },
	bgLightBlue: { background: 'var(--light-theme-primary)' },
	bgLightPink: { background: 'var(--light-pink)' },
	bgLightPurple: { background: 'var(--light-purple)' },
	bgGray: { background: 'var(--gray)' },
	bgPage: { background: '#e5e5e5' },
	bgRed: { background: 'var(--background-red)' },
	bgBlue: { background: 'var(--background-blue)' },
	fontExtraLight: { fontFamily: '"Poppins", "Roboto", sans-serif', fontWeight: '200' },
	fontLight: { fontFamily: '"Poppins", "Roboto", sans-serif', fontWeight: '300' },
	fontRegular: { fontFamily: '"Poppins", "Roboto", sans-serif', fontWeight: '400' },
	fontMedium: { fontFamily: '"Poppins", "Roboto", sans-serif', fontWeight: '500' },
	fontHeavy: { fontFamily: '"Poppins", "Roboto", sans-serif', fontWeight: '700' },
	fontExtraHeavy: { fontFamily: '"Poppins", "Roboto", sans-serif', fontWeight: '800' },
	font900: { fontWeight: '900' },
	dspInb: { display: 'inline-block' },
	dspB: { display: 'block' },
	dspN: { display: 'none' },
	dspIn: { display: 'inline' },
	dspFl: { display: 'flex' },
	fs4: { fontSize: '0.25rem' },
	fs8: { fontSize: '0.5rem' },
	fs10: { fontSize: '0.625rem' },
	fs11: { fontSize: '0.6875rem' },
	fs12: { fontSize: '0.75rem !important' },
	fs13: { fontSize: '0.8125rem' },
	fs14: { fontSize: '0.875rem' },
	fs15: { fontSize: '0.9375rem' },
	fs16: { fontSize: '1rem' },
	fs18: { fontSize: '1.125rem' },
	fs20: { fontSize: '1.25rem' },
	fs22: { fontSize: '1.375rem' },
	fs24: { fontSize: '1.5rem' },
	fs28: { fontSize: '1.75rem' },
	fs32: { fontSize: '2rem' },
	fs36: { fontSize: '2.25rem' },
	fs40: { fontSize: '2.5rem' },
	fs44: { fontSize: '2.75rem' },
	fs48: { fontSize: '3rem' },
	borderBottom: {
		border: 'none !important',
		borderBottom: '1px solid var(--border-color) !important',
	},
	borderRight: {
		border: 'none !important',
		borderRight: '1px solid var(--border-color) !important',
	},
	borderLeft: {
		border: 'none !important',
		borderLeft: '1px solid var(--border-color) !important',
	},
	borderTopBottom: {
		borderTop: '1px solid var(--border-color) !important',
		borderBottom: '1px solid var(--border-color) !important',
	},
	borderTop: {
		border: 'none !important',
		borderTop: '1px solid var(--border-color) !important',
	},
	heavyBorder: { border: '3px solid var(--border-color)' },
	pinkBorder: {
		border: '1px solid var(--pink)',
		borderColor: 'var(--pink) !important',
	},
	fullBorder: {
		border: '1px solid var(--border-color)',
		'&.border-primary': { borderColor: 'var(--theme-primary)' },
	},
	dashedBorderBottom: {
		borderBottom: '1px dashed var(--border-color) !important',
	},
	dashedBorderTop: { borderTop: '1px dashed var(--border-color) !important' },
	dashedBorder: { border: '1px dashed var(--border-color) !important' },
	borderRed: { borderColor: 'var(--red) !important' },
	blueBorder: { borderColor: 'var(--theme-primary) !important' },
	grayBorder: { borderColor: 'var(--light-gray) !important' },
	whiteBorder: { borderColor: 'var(--white) !important' },
	br7: { borderRadius: '7px' },
	br9: { borderRadius: '9px' },
	br10: { borderRadius: '10px' },
	br12: { borderRadius: '12px' },
	br100: { borderRadius: '100%' },
	noBorder: { border: 'none' },
	mr0: { margin: '0px !important' },
	mr5: { margin: '5px' },
	mr10: { margin: '10px' },
	mr15: { margin: '15px' },
	mr20: { margin: '20px' },
	mr25: { margin: '20px' },
	mr30: { margin: '30px' },
	mrT0: { marginTop: '0px' },
	mrT5: { marginTop: '5px' },
	mrT7: { marginTop: '7px' },
	mrT10: { marginTop: '10px' },
	mrT15: { marginTop: '15px' },
	mrT20: { marginTop: '20px' },
	mrT25: { marginTop: '20px' },
	mrT27: { marginTop: '27px' },
	mrT30: { marginTop: '30px' },
	mrT37: { marginTop: '37px' },
	mrT65: { marginTop: '65px' },
	mrB0: { marginBottom: '0px' },
	mrB5: { marginBottom: '5px' },
	mrB10: { marginBottom: '10px' },
	mrB15: { marginBottom: '15px' },
	mrB12: { marginBottom: '12px' },
	mrB20: { marginBottom: '20px' },
	mrB25: { marginBottom: '20px' },
	mrB30: { marginBottom: '30px' },
	mrB50: { marginBottom: '50px' },
	mrL0: { marginLeft: '0px' },
	mrL4: { marginLeft: '4vw' },
	mrL5: { marginLeft: '5px' },
	mrL10: { marginLeft: '10px' },
	mrL15: { marginLeft: '15px' },
	mrL20: { marginLeft: '20px' },
	mrL25: { marginLeft: '20px' },
	mrL30: { marginLeft: '30px' },
	mrR0: { marginRight: '0px' },
	mrR5: { marginRight: '5px' },
	mrR10: { marginRight: '10px' },
	mrR15: { marginRight: '15px' },
	mrR20: { marginRight: '20px' },
	mrR25: { marginRight: '25px' },
	mrR30: { marginRight: '30px' },
	mrH0: { marginLeft: '0px', marginRight: '0px' },
	mrH5: { marginLeft: '5px', marginRight: '5px' },
	mrH10: { marginLeft: '10px', marginRight: '10px' },
	mrH15: { marginLeft: '15px', marginRight: '15px' },
	mrH20: { marginLeft: '20px', marginRight: '20px' },
	mrH25: { marginLeft: '20px', marginRight: '20px' },
	mrH30: { marginLeft: '30px', marginRight: '30px' },
	mrV0: { marginTop: '0px', marginBottom: '0px' },
	mrV5: { marginTop: '5px', marginBottom: '5px' },
	mrV10: { marginTop: '10px', marginBottom: '10px' },
	mrV15: { marginTop: '15px', marginBottom: '15px' },
	mrV20: { marginTop: '20px', marginBottom: '20px' },
	mrV25: { marginTop: '20px', marginBottom: '20px' },
	mrV30: { marginTop: '30px', marginBottom: '30px' },
	pd0: { padding: '0px !important' },
	pd5: { padding: '5px' },
	pd7: { padding: '7px' },
	pd10: { padding: '10px !important' },
	pd15: { padding: '15px' },
	pd20: { padding: '20px' },
	pd25: { padding: '20px' },
	pd30: { padding: '30px' },
	pdT0: { paddingTop: '0px' },
	pdT5: { paddingTop: '5px' },
	pdT10: { paddingTop: '10px' },
	pdT15: { paddingTop: '15px' },
	pdT20: { paddingTop: '20px' },
	pdT25: { paddingTop: '20px' },
	pdT30: { paddingTop: '30px' },
	pdB0: { paddingBottom: '0px' },
	pdB2: { paddingBottom: '2px' },
	pdB5: { paddingBottom: '5px' },
	pdB10: { paddingBottom: '10px' },
	pdB15: { paddingBottom: '15px' },
	pdB20: { paddingBottom: '20px' },
	pdB25: { paddingBottom: '20px' },
	pdB30: { paddingBottom: '30px' },
	pdB50: { paddingBottom: '50px' },
	pdL0: { paddingLeft: '0px' },
	pdL5: { paddingLeft: '5px' },
	pdL10: { paddingLeft: '10px' },
	pdL15: { paddingLeft: '15px' },
	pdL20: { paddingLeft: '20px' },
	pdL25: { paddingLeft: '20px' },
	pdL30: { paddingLeft: '30px' },
	pdL35: { paddingLeft: '35px' },
	pdL40: { paddingLeft: '40px' },
	pdR0: { paddingRight: '0px' },
	pdR5: { paddingRight: '5px' },
	pdR10: { paddingRight: '10px' },
	pdR15: { paddingRight: '15px' },
	pdR20: { paddingRight: '20px' },
	pdR25: { paddingRight: '20px' },
	pdR30: { paddingRight: '30px' },
	pdH0: { paddingLeft: '0px !important', paddingRight: '0px !important' },
	pdH5: { paddingLeft: '5px', paddingRight: '5px' },
	pdH10: { paddingLeft: '10px', paddingRight: '10px' },
	pdH15: { paddingLeft: '15px', paddingRight: '15px' },
	pdH20: { paddingLeft: '20px', paddingRight: '20px' },
	pdH25: { paddingLeft: '20px', paddingRight: '20px' },
	pdH30: { paddingLeft: '30px', paddingRight: '30px' },
	pdV0: { paddingTop: '0px', paddingBottom: '0px' },
	pdV5: { paddingTop: '5px', paddingBottom: '5px' },
	pdV10: { paddingTop: '10px !important', paddingBottom: '10px !important' },
	pdV15: { paddingTop: '15px !important', paddingBottom: '15px !important' },
	pdV20: { paddingTop: '20px !important', paddingBottom: '20px !important' },
	pdV25: { paddingTop: '20px', paddingBottom: '20px' },
	pdV30: { paddingTop: '30px', paddingBottom: '30px' },
	pd3: { padding: '3px' },
	h85vh: { height: '85vh' },
	h100vh: { height: '100vh' },
	h45: { height: '45vh' },
	h50: { height: '50vh' },
	h70: { height: '70vh' },
	h75: { height: '75vh' },
	h80: { height: '80vh' },
	h100: { height: '100%' },
	h5: { height: '5%' },
	h15: { height: '15%' },
	h30: { height: '30%' },
	mh0: { maxHeight: '0px', overflow: 'hidden' },
	mh200: { maxHeight: '500px' },
	w0: { width: '0% !important' },
	w3: { width: '3% !important' },
	w5: { width: '5% !important' },
	w6: { width: '6% !important' },
	w7: { width: '7% !important' },
	w8: { width: '8% !important' },
	w10: { width: '10% !important' },
	w12: { width: '12% !important' },
	w15: { width: '15% !important' },
	w20: { width: '20% !important' },
	w23: { width: '23% !important' },
	w25: { width: '25% !important' },
	w27: { width: '27% !important' },
	w30: { width: '30% !important' },
	w33: { width: '33.3% !important' },
	w35: { width: '35%' },
	w40: { width: '40% !important' },
	w45: { width: '45% !important' },
	w47: { width: '47%' },
	w48: { width: '48%' },
	w50: { width: '50%' },
	w55: { width: '55%' },
	w60: { width: '60%' },
	w65: { width: '65%' },
	w70: { width: '70%' },
	w75: { width: '75%' },
	w80: { width: '80% !important' },
	w85: { width: '85%' },
	w90: { width: '90%' },
	w95: { width: '95%' },
	w97: { width: '97%' },
	c1f: { color: '#1F1F1F' },
	fcg: { color: '#4F4F4F' },
	w100: { width: '100%' },
	w100Imp: { width: '100% !important' },
	maxWidth: { width: 'max-content' },
	textRight: { textAlign: 'right' },
	textLeft: { textAlign: 'left' },
	textCenter: { textAlign: 'center' },
	textJustify: { textAlign: 'justify' },
	lh20: { lineHeight: '20px' },
	lh24: { lineHeight: '24px' },
	lh32: { lineHeight: '32px' },
	lh35: { lineHeight: '35px' },
	posAbs: { position: 'absolute' },
	posRel: { position: 'relative' },
	posFix: { position: 'fixed' },
	justifyEnd: { justifyContent: 'flex-end' },
	justifyBetween: { justifyContent: 'space-between' },
	justifyEvenly: { justifyContent: 'space-evenly' },
	justifyAround: { justifyContent: 'space-around' },
	justifyCenter: { justifyContent: 'center' },
	alignCenter: { alignItems: 'center' },
	alignTop: { alignItems: 'flex-start' },
	alignEnd: { alignItems: 'flex-end' },
	flexColumn: { flexDirection: 'column' },
	flexWrap: { flexWrap: 'wrap' },
	rotate180: { transform: 'rotate(180deg)' },
	rotate90: { transform: 'rotate(90deg)' },
	disabled: { pointerEvents: 'none', opacity: 0.5 },
	clearfix: {
		display: 'inline-block',
		':after': {
			visibility: 'hidden',
			display: 'block',
			fontSize: '0',
			content: "' '",
			clear: 'both',
			height: '0',
		},
	},
	bottomLine: {
		height: '1px',
		background: 'rgba(0, 0, 0, 0.1)',
		border: 'none',
		margin: '0',
	},
	underline: { textDecoration: 'underline' },
	italic: { fontStyle: 'italic' },
	noWrap: { whiteSpace: 'nowrap' },
	z10: { zIndex: 10 },
	z100: { zIndex: 100 },
	noLetterSpacing: { letterSpacing: 'normal' },
	overflowHdn: { overflow: 'hidden' },
	overflowHdnImp: { overflow: 'hidden !important' },
	overflowScroll: { overflow: 'scroll' },
	overflowAuto: { overflow: 'auto' },
	wordBreak: { wordBreak: 'break-all' },
	transition: { transition: 'all 0.5s ease-in-out' },
	uppercase: { textTransform: 'uppercase' },
	capitalize: { textTransform: 'capitalize' },
	ellipsis: {
		maxWidth: '90%',
		whiteSpace: 'nowrap',
		overflow: 'hidden',
		textOverflow: 'ellipsis',
	},
	o0: { opacity: 0 },
	noShadow: { boxShadow: 'none !important' },
	textCaseDefault: { textTransform: 'none' },
	verticalMiddle: { verticalAlign: 'middle' },
	successNote: {
		background: '#e9f8ff',
		border: '1px solid #009cde',
		color: '#009cde',
	},
	pendingNote: {
		background: 'var(--light-yellow)',
		border: '1px solid var(--yellow)',
	},
};
